CREATE TABLE PP_TRANSACTION_EMAIL(
    ID                   NUMBER NOT NULL,
    FK_TRANSACTION       NUMBER NOT NULL,
    REQUEST_TMS TIMESTAMP NOT NULL,
    SENDING_TMS TIMESTAMP,
    LAST_ATTEMPT_TMS TIMESTAMP,
    CONTEXT VARCHAR2(40 CHAR),
    STATUS NUMBER(2,0),
    BATCH_RETRY_ATTEMPTS_COUNT NUMBER DEFAULT 0,
    KO_REASON VARCHAR2(500 CHAR),
    CONSTRAINT PK_TRANSACTION_EMAIL PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_TRANSACTION_EMAIL
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE INDEX PP_TR_EMAIL_FK_TR_IDX ON PP_TRANSACTION_EMAIL (FK_TRANSACTION) TABLESPACE AGID_DATA;
CREATE INDEX PP_TR_EMAIL_STATUS_IDX ON PP_TRANSACTION_EMAIL (STATUS) TABLESPACE AGID_DATA;
CREATE INDEX PP_TR_EMAIL_REQ_TMS_IDX ON PP_TRANSACTION_EMAIL (REQUEST_TMS) TABLESPACE AGID_DATA;

ALTER TABLE PP_TRANSACTION_EMAIL ADD CONSTRAINT FK_TRANSACTION_EMAIL FOREIGN KEY (FK_TRANSACTION)
 REFERENCES PP_TRANSACTION (ID);
