-- creation of postepay psp details table
CREATE TABLE PP_POSTEPAY_PSP_DETAILS(
    ID                   NUMBER(9, 0) NOT NULL,
    ID_PSP               VARCHAR2(128 BYTE) UNIQUE NOT NULL,
    PSP_URL              VARCHAR2(128 BYTE) NOT NULL,
	PRIVACY_TERMS_URL 	 VARCHAR2(128),
    CONSTRAINT PK_POSTEPAY_PSP_DETAILS PRIMARY KEY (ID)
);

-- Create sequence "SEQ_POSTEPAY_PSP_DETAILS"
CREATE SEQUENCE SEQ_POSTEPAY_PSP_DETAILS
START WITH 1
INCREMENT BY 1
NOCACHE;
