-- Create sequence "SEQ_POSTEPAY"
CREATE SEQUENCE SEQ_POSTEPAY
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Create of postepay table
CREATE TABLE PP_POSTEPAY (
	ID NUMBER(9,0) NOT NULL,
	ID_PPAY VARCHAR2(128) NOT NULL,
	LAST_UPDATE_DATE TIMESTAMP NOT NULL,
	IS_CANCELED NUMBER(1,0) DEFAULT 0 NOT NULL,
	IS_DEFAULT NUMBER(1,0) DEFAULT 0 NOT NULL,
	FK_WALLET NUMBER(9,0) NOT NULL,
	ID_PSP VARCHAR2(128) NOT NULL,
	CONSTRAINT PK_POSTEPAY PRIMARY KEY (ID),
	CONSTRAINT PP_POSTEPAY_WALLET_FK FOREIGN KEY (FK_WALLET) REFERENCES PP_WALLET (ID_WALLET)
);

CREATE UNIQUE INDEX POSTEPAY_UNIQUE_WALLET_PSP ON PP_POSTEPAY (  CASE WHEN IS_CANCELED = 0 THEN FK_WALLET end,CASE WHEN IS_CANCELED = 1 THEN  ID_PSP end);
CREATE INDEX PP_POSTEPAY_WALLET_IDX ON PP_POSTEPAY(FK_WALLET);