CREATE SEQUENCE SEQ_EVENTO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_WISP
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE EVENTO_WISP (
ID NUMBER,
SHORT_NAME VARCHAR2(50) NOT NULL,
DESCRIPTION VARCHAR2(100) NULL,
CONSTRAINT EVENTO_WISP_PK PRIMARY KEY (ID),
CONSTRAINT event_unique_short_name UNIQUE (SHORT_NAME)
);

CREATE TABLE RE_WISP (
ID NUMBER,
PP_PAYMENT_ID NUMBER NOT NULL,
PP_USER_ID NUMBER NULL,
PP_WALLET_ID NUMBER NULL,
EVENTO_WISP_ID NUMBER NOT NULL,
PP_SESSION_TOKEN VARCHAR2(128 BYTE),
EVENT_TIME TIMESTAMP NOT NULL,
DETAILS CLOB,
CONSTRAINT RE_WISP_PK PRIMARY KEY (ID),
CONSTRAINT FK_UEVENT_EVENT FOREIGN KEY (EVENTO_WISP_ID) REFERENCES EVENTO_WISP(ID)
);
CREATE INDEX RE_WISP_PP_PAYMENT_ID_IDX ON EVENT_REGISTRY.RE_WISP (PP_PAYMENT_ID) TABLESPACE EVENT_REGISTRY_IDX;
CREATE INDEX RE_WISP_PP_USER_ID_IDX ON EVENT_REGISTRY.RE_WISP (PP_USER_ID) TABLESPACE EVENT_REGISTRY_IDX;

ALTER TABLE RE_WISP ADD ID_PAYMENT VARCHAR2(128 BYTE);
CREATE INDEX RE_WISP_ID_PAYMENT_IDX ON EVENT_REGISTRY.RE_WISP (ID_PAYMENT) TABLESPACE EVENT_REGISTRY_IDX;

ALTER TABLE RE_WISP
ADD RE_WISP_REMOTE_ID NUMBER;

CREATE INDEX RE_WISP_RE_WISP_REMOTE_ID_IDX ON EVENT_REGISTRY.RE_WISP (RE_WISP_REMOTE_ID ASC, 1) TABLESPACE EVENT_REGISTRY_IDX;

ALTER TABLE EVENTO_WISP
ADD SYNC_TO_REMOTE_RE NUMBER(1,0) DEFAULT 0;

ALTER TABLE EVENTO_WISP
ADD EVENTO_WISP_REMOTE_ID NUMBER;
