version: '3.8'

services:
  pagopa-ecommerce-helpdesk:
    container_name: pagopa-ecommerce-helpdesk
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - pagopa-ecommerce-net

networks:
  pagopa-ecommerce-net:
    name: pagopa-ecommerce-net
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450


