CREATE SEQUENCE SEQ_EVENTO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_WISP
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE EVENTO_WISP (
ID NUMBER,
SHORT_NAME VARCHAR2(50) NOT NULL,
DESCRIPTION VARCHAR2(100) NULL,
CONSTRAINT EVENTO_WISP_PK PRIMARY KEY (ID),
CONSTRAINT event_unique_short_name UNIQUE (SHORT_NAME)
);

CREATE TABLE RE_WISP (
ID NUMBER,
PP_PAYMENT_ID NUMBER NOT NULL,
PP_USER_ID NUMBER NULL,
PP_WALLET_ID NUMBER NULL,
EVENTO_WISP_ID NUMBER NOT NULL,
PP_SESSION_TOKEN VARCHAR2(128 BYTE),
EVENT_TIME TIMESTAMP NOT NULL,
DETAILS CLOB,
ID_PAYMENT VARCHAR2(128 BYTE),
CONSTRAINT RE_WISP_PK PRIMARY KEY (ID),
CONSTRAINT FK_UEVENT_EVENT FOREIGN KEY (EVENTO_WISP_ID) REFERENCES EVENTO_WISP(ID)
);

CREATE INDEX RE_WISP_REMOTE_PP_PAYMENT_ID_IDX ON RE_WISP (PP_PAYMENT_ID);
CREATE INDEX RE_WISP_REMOTE_PP_USER_ID_IDX ON RE_WISP (PP_USER_ID);
CREATE INDEX RE_WISP_REMOTE_ID_PAYMENT_IDX ON RE_WISP (id_payment);