DROP INDEX RE_WISP_REMOTE_PP_PAYMENT_ID_IDX;
DROP INDEX RE_WISP_REMOTE_PP_USER_ID_IDX;
DROP INDEX RE_WISP_REMOTE_ID_PAYMENT_IDX;

ALTER TABLE RE_WISP DROP CONSTRAINT RE_WISP_PK DROP INDEX;
ALTER TABLE RE_WISP DROP CONSTRAINT FK_UEVENT_EVENT DROP INDEX;

ALTER TABLE RE_WISP RENAME TO RE_WISP_OLD;

CREATE TABLE RE_WISP (
ID NUMBER,
PP_PAYMENT_ID NUMBER NOT NULL,
PP_USER_ID NUMBER NULL,
PP_WALLET_ID NUMBER NULL,
EVENTO_WISP_ID NUMBER NOT NULL,
PP_SESSION_TOKEN VARCHAR2(128 BYTE),
EVENT_TIME TIMESTAMP NOT NULL,
DETAILS CLOB,
ID_PAYMENT VARCHAR2(128 BYTE),
CONSTRAINT RE_WISP_PK PRIMARY KEY (ID),
CONSTRAINT FK_UEVENT_EVENT FOREIGN KEY (EVENTO_WISP_ID) REFERENCES EVENTO_WISP(ID)
)
PARTITION BY RANGE (EVENT_TIME)
INTERVAL (NUMTODSINTERVAL(1, 'day'))
(
    PARTITION "RE_WISP_1"  VALUES LESS THAN (TIMESTAMP' 2019-04-01 00:00:00')
);

CREATE INDEX RE_WISP_REMOTE_PP_PAYMENT_ID_IDX ON RE_WISP (PP_PAYMENT_ID);
CREATE INDEX RE_WISP_REMOTE_PP_USER_ID_IDX ON RE_WISP (PP_USER_ID);
CREATE INDEX RE_WISP_REMOTE_ID_PAYMENT_IDX ON RE_WISP (id_payment);

INSERT INTO RE_WISP (
    ID,
    PP_PAYMENT_ID,
    PP_USER_ID,
    PP_WALLET_ID,
    EVENTO_WISP_ID,
    PP_SESSION_TOKEN,
    EVENT_TIME,
    DETAILS,
    ID_PAYMENT
)
SELECT
    ID,
    PP_PAYMENT_ID,
    PP_USER_ID,
    PP_WALLET_ID,
    EVENTO_WISP_ID,
    PP_SESSION_TOKEN,
    EVENT_TIME,
    DETAILS,
    ID_PAYMENT
FROM
    RE_WISP_OLD;

DROP TABLE RE_WISP_OLD;