--insert postepay psp detail [ONLY FOR LOCAL ENVIRONMENT]
INSERT INTO PP_POSTEPAY_PSP_DETAILS
(ID, ID_PSP, PSP_URL)
VALUES(SEQ_POSTEPAY_PSP_DETAILS.nextval, 'PPAY_LOCAL', 'local000');

-- insert postepay psp into pp_psp [ONLY FOR LOCAL ENVIRONMENT]
INSERT INTO PP_PSP
(ID, ID_PSP, BUSINESS_NAME, PAYMENT_TYPE, ID_INTERMEDIARY, ID_CHANNEL, LOGO_PSP, SERVICE_LOGO, SERVICE_NAME, FIXED_COST, APP_CHANNEL, SERICE_DESCRIPTION, TAGS, SERVICE_AVAILABILITY, URL_INFO_CHANNEL, FLAG_STAMP, ID_CARD, LOB_LOGO_PSP, LOB_SERVICE_LOGO, PAYMENT_MODEL, IS_CANCELLED, "LANGUAGE", CODICE_ABI, PARTICIPANT, CODICE_CONVENZIONE)
VALUES(SEQ_PSP.nextval, 'PPAY_LOCAL', 'PPAY_LOCAL', 'PPAY', 'POSTEPAY PSP', 'POSTEPAY 1', NULL, NULL, 'ppaylocal', 100, 0, 'description', NULL, 'available', NULL, 1, 12001, NULL, NULL, 1, 0, 'IT', '01234', NULL, NULL);
