INSERT
INTO PP_USER
(ID_USER,
 USERNAME,
 EMAIL,
 STATUS,
 NAME,
 SURNAME,
 CELLPHONE,
 LAST_ACCESS,
 IS_EMAIL_VERIFIED,
 EMAIL_LINK_VALIDATION,
 EMAIL_LINK_RESET_PASSWORD,
 IS_CELLPHONE_VERIFIED,
 FLAG_TERMS,
 FLAG_CONDITION,
 CREATION_DATE,
 UPDATE_DATE,
 PASSWORD,
 PUK,
 TOKEN_PUK_VERIFIED,
 REGISTERED_DATE,
 TEMPORARY_CELLPHONE,
 BO_TEMPORARY_PASSWORD,
 BO_TEMPORARY_PASSWORD_TOKEN,
 BO_TEMPORARY_PUK,
 BO_TEMPORARY_PUK_TOKEN,
 BO_TEMPORARY_EMAIL,
 BO_TEMPORARY_EMAIL_TOKEN,
 ACTIVATION_DATE,
 NOTIFICATION_EMAIL,
 FISCAL_CODE)
VALUES (1,
        'username',
        'test@test.it',
        11,
        'name',
        'surname',
        NULL,
        TIMESTAMP '2018-06-25 15:19:51.748000',
        0,
        NULL,
        NULL,
        0,
        1,
        1,
        TIMESTAMP '2018-06-25 15:19:51.748000',
        TIMESTAMP '2018-06-26 12:41:29.054000',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'test@test.it',
        'fiscal_code');

INSERT INTO PP_CREDIT_CARD
(ID_CREDIT_CARD,
 CARD_BIN,
 FL_ENABLED,
 CREATION_DATE,
 LAST_UPDATE_DATE,
 ID_USER,
 CARD_NUMBER,
 FK_CREDIT_CARD_STATUS,
 FL_DEFAULT,
 FL_VISIBLE,
 FL_3DS_VERIFIED,
 CC_CHECKER,
 OLD_PAN_START,
 OLD_EXPIRE_DATE,
 OLD_CARD_HOLDER,
 VPOS_CIRCUIT_CODE,
 OLD_HPAN,
 HAS_ALREADY_PAID,
 ABI,
 "TYPE",
 FL_FORWARD_CREATE_CARD_TO_TKM,
 FL_FORWARD_DELETE_CARD_TO_TKM,
 ID_S4S_KEY,
 PAN_START,
 EXPIRE_DATE,
 CARD_HOLDER,
 HPAN)
VALUES (1,
        '1234',
        1,
        TIMESTAMP '2000-10-22 19:03:25.979000',
        TIMESTAMP '2000-10-22 19:03:25.979000',
        1,
        '*************1234',
        0,
        0,
        1,
        0,
        '',
        '',
        '',
        '',
        '',
        '',
        0,
        '',
        '',
        0,
        0,
        1,
        '',
        '',
        '',
        '');

INSERT INTO PP_GENERIC_INSTRUMENT
(ID,
 OLD_UID_INSTRUMENT,
 OLD_UID_INSTRUMENT_HASH,
 BRAND,
 DESCRIPTION,
 ADDITIONAL_INFO,
 ADDITIONAL_INFO_2,
 ID_USER,
 ID_S4S_KEY,
 UID_INSTRUMENT,
 UID_INSTRUMENT_HASH)
VALUES (1,
        '',
        '',
        '',
        'Generic instrument',
        '',
        '',
        1,
        1,
        '',
        '');

INSERT INTO PP_WALLET
(ID_WALLET,
 "TYPE",
 ID_USER,
 FK_CREDIT_CARD,
 FK_BANK_ACCOUNT,
 FL_DEFAULT,
 FL_ENABLED,
 CREATION_DATE,
 FL_VISIBLE,
 FK_EXTERNAL_PS,
 FK_PSP,
 FL_PSP_EDITABLE,
 LAST_USAGE_DATE,
 JIFFY_CELLPHONE_NUMBER,
 IS_PSP_TO_IGNORE,
 FK_BUYER_BANK,
 CONTRACT_NUMBER,
 ONBOARDING_CHANNEL,
 FK_BANCOMAT_CARD,
 FK_SATISPAY,
 FK_BPAY,
 FK_GENERIC_INSTRUMENT,
 PAGOPA)
VALUES (1,
        1,
        1,
        1, -- PP_CREDIT_CARD
        NULL,
        1,
        1,
        TIMESTAMP '2000-10-22 19:03:25.979000',
        1,
        NULL,
        1,
        1,
        TIMESTAMP '2000-10-22 19:03:25.979000',
        NULL,
        0,
        NULL, -- PP_MYBANK_BUYER_BANK
        NULL,
        NULL,
        NULL, -- PP_BANCOMAT_CARD
        NULL, -- PP_SATISPAY
        NULL, -- PP_BPAY
        NULL, -- PP_GENERIC_INSTRUMENT
        1);

INSERT
INTO PP_PAYMENT
(ID,
 ID_PAYMENT,
 AMOUNT,
 EMAIL,
 SUBJECT,
 RECEIVER,
 CREATION_DATE,
 UPDATE_DATE,
 URL_REDIRECT_EC,
 IS_CANCELLED,
 IS_NOT_NOTIFIED,
 RETRY_COUNT,
 BOLLO_DIGITALE,
 CREDIT_CARD_VERIFICATION,
 FISCAL_CODE,
 ORIGIN,
 ID_CARRELLO,
 IBAN)
VALUES (1,
        'ac4f1d71-db20-4c10-9059-afbee92ff83f',
        10,
        NULL,
        '/RFB/718173815252003/0.10/TXT/Pagamento di test 20',
        'Comune di Milano',
        TIMESTAMP '2018-06-25 12:35:26.976000',
        TIMESTAMP '2018-06-25 12:35:26.976000',
        'http://test.it:80/pagamenti?idSession=...',
        0,
        0,
        0,
        0,
        0,
        NULL,
        'origin',
        NULL,
        NULL);

INSERT
INTO PP_PAYMENT_DETAIL
(ID,
 PAYMENT_ID,
 IUV,
 CCP,
 ID_DOMINIO,
 ENTE_BENEFICIARIO,
 IMPORTO,
 TIPO_PAGATORE,
 CODICE_PAGATORE,
 NOME_PAGATORE)
VALUES (1,
        1,
        '000000044060814',
        'MIUR20191119222949',
        '97061100588',
        'RMIC81500N',
        100,
        NULL,
        NULL,
        NULL);

INSERT
INTO PP_TRANSACTION
(ID,
 FK_USER,
 FK_PAYMENT,
 FK_WALLET,
 AMOUNT,
 FEE,
 STATUS,
 CREATION_DATE,
 UPDATE_DATE,
 GRAND_TOTAL,
 FK_PSP,
 ACCOUNTING_STATUS,
 SPC_NODE_STATUS,
 SPC_NODE_DESCRIPTION,
 ACCOUNT_CODE,
 ACCOUNT_ATTEMPT,
 AUTHORIZATION_CODE,
 FK_BUSINESS_NAME,
 SERVICE_NAME,
 ID_CHANNEL,
 MANUAL_JOB_PROCESSED,
 MANUAL_JOB_DATE,
 MANUAL_JOB_RESULT,
 RRN,
 NUMAUT,
 TX_REVERT_RETRY_COUNT,
 ID_PSP,
 CODICE_ABI,
 OUTCOME,
 "LANGUAGE",
 EMAIL_NOTIFICATION_EVENT)
VALUES (1,
        1,
        1,
        1,
        100,
        50,
        2,
        TIMESTAMP '2018-06-26 17:05:36.232000',
        TIMESTAMP '2018-06-26 17:05:36.232000',
        150,
        1,
        1,
        1,
        NULL,
        NULL,
        1,
        'auth code',
        NULL,
        'payment method name',
        NULL,
        1,
        NULL,
        NULL,
        'rrn',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL);

INSERT INTO PP_BANCOMAT_CARD
(ID_BANCOMAT_CARD,
 OLD_CARD_NUMBER,
 CARD_PARTIAL_NUMBER,
 OLD_EXPIRING_DATE,
 PRODUCT_TYPE,
 VALIDITY_STATE,
 ABI,
 TOKEN_HASHES,
 OLD_TOKENS,
 OLD_HPAN,
 ID_USER,
 ID_S4S_KEY,
 CARD_NUMBER,
 EXPIRING_DATE,
 HPAN,
 TOKENS)
VALUES (1,
        '',
        'cardPartialNumber',
        '',
        '',
        '',
        'abi',
        '',
        '',
        '',
        0,
        1,
        '',
        '',
        '',
        '');

INSERT INTO PP_BPAY
(ID_BPAY,
 GROUP_CODE,
 INSTITUTE_CODE,
 BANK_NAME,
 NAME,
 SURNAME,
 CELLPHONE_NUMBER,
 CELLPHONE_NUMBER_ENCRYPTED,
 UID_BPAY,
 OLD_UID_HASH,
 SERVICE_STATE,
 ID_USER,
 ID_S4S_KEY,
 UID_HASH)
VALUES (1,
        '',
        '',
        'bankName',
        '',
        '',
        'cellPhoneNumber',
        '',
        '',
        '',
        '',
        0,
        1,
        '');

INSERT INTO PP_PAYPAL
(ID,
 EMAIL_PP,
 ID_PP,
 LAST_UPDATE_DATE,
 IS_CANCELED,
 IS_DEFAULT,
 FK_WALLET,
 ID_PSP)
VALUES (1,
        'test@test.it',
        'TEST',
        TIMESTAMP '2000-10-22 19:03:25.979000',
        0,
        0,
        1,
        'TEST');

INSERT INTO PP_SATISPAY
(ID_SATISPAY,
 UID_SATISPAY,
 OLD_UID_SATISPAY_HASH,
 ID_USER,
 ID_S4S_KEY,
 UID_SATISPAY_HASH)
VALUES (1,
        '',
        '',
        1,
        1,
        '');