microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopapcommonacr.azurecr.io/pagopaecommercehelpdeskservice
        tag: "latest"
        pullPolicy: Always
    envConfig:
      DEFAULT_LOGGING_LEVEL: "info"
      APP_LOGGING_LEVEL: "info"
      WEB_LOGGING_LEVEL: "off"
      ECS_SERVICE_NAME: "pagopa-ecommerce-helpdesk-service-blue"
      ECS_SERVICE_ENVIRONMENT: "prod"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-helpdesk-service-blue,deployment.environment=prod"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
      OTEL_LOGS_EXPORTER: none
      OTEL_TRACES_SAMPLER: "always_on"
      PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.tokenizer.pdv.pagopa.it/tokenizer/v1"
      PM_ORACLE_PORT: "1523"
      PM_ORACLE_DATABASE_NAME: "AZAGIDP"
      PM_ORACLE_USERNAME: "PAGOPA_SV"
      MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account-northeurope.mongo.cosmos.azure.com
      MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
      MONGO_PORT: "10256"
      MONGO_SSL_ENABLED: "true"
      MONGO_MIN_POOL_SIZE: "0"
      MONGO_MAX_POOL_SIZE: "50"
      MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
      MONGO_CONNECTION_TIMEOUT_MS: "2000"
      MONGO_SOCKET_TIMEOUT_MS: "10000"
      MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
      MONGO_WAITING_QUEUE_MS: "2000"
      MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
      SEARCH_DEAD_LETTER_QUEUE_MAPPING: >
        {ALL: '*', ECOMMERCE: 'pagopa-p-weu-ecommerce-transactions-dead-letter-queue', NOTIFICATIONS_SERVICE: 'pagopa-p-weu-ecommerce-notifications-service-errors-queue'}

    envSecret:
      OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
      PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
      PM_ORACLE_PASSWORD: pm-oracle-db-password
      PM_ORACLE_HOST: pm-oracle-db-host
      MONGO_PASSWORD: mongo-ecommerce-password
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaecommercehelpdeskservice
    tag: "1.7.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 100
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 100
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.platform.pagopa.it"
    path: /pagopa-ecommerce-helpdesk-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    DEFAULT_LOGGING_LEVEL: "info"
    APP_LOGGING_LEVEL: "info"
    WEB_LOGGING_LEVEL: "off"
    ECS_SERVICE_NAME: "pagopa-ecommerce-helpdesk-service"
    ECS_SERVICE_ENVIRONMENT: "prod"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-helpdesk-service,deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.tokenizer.pdv.pagopa.it/tokenizer/v1"
    PM_ORACLE_PORT: "1523"
    PM_ORACLE_DATABASE_NAME: "AZAGIDP"
    PM_ORACLE_USERNAME: "PAGOPA_SV"
    MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account-northeurope.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
    MONGO_PORT: "10256"
    MONGO_SSL_ENABLED: "true"
    MONGO_MIN_POOL_SIZE: "0"
    MONGO_MAX_POOL_SIZE: "50"
    MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
    MONGO_CONNECTION_TIMEOUT_MS: "2000"
    MONGO_SOCKET_TIMEOUT_MS: "10000"
    MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
    MONGO_WAITING_QUEUE_MS: "2000"
    MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
    SEARCH_DEAD_LETTER_QUEUE_MAPPING: >
      {ALL: '*', ECOMMERCE: 'pagopa-p-weu-ecommerce-transactions-dead-letter-queue', NOTIFICATIONS_SERVICE: 'pagopa-p-weu-ecommerce-notifications-service-errors-queue'}

  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
    PM_ORACLE_PASSWORD: pm-oracle-db-password
    PM_ORACLE_HOST: pm-oracle-db-host
    MONGO_PASSWORD: mongo-ecommerce-password
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopaecommercehelpdeskservice
            namespaces: ["ecommerce"]
            topologyKey: topology.kubernetes.io/zone
