DECLARE
	MAX_ID NUMBER;
BEGIN

SELECT COALESCE(MAX(ID),0) + 1 INTO MAX_ID FROM RE_WISP;
EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_WISP RESTART START WITH ' || MAX_ID;
SELECT COALESCE(MAX(ID),0) + 1 INTO MAX_ID FROM EVENTO_WISP;
EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_EVENTO RESTART START WITH ' || MAX_ID;

END;
/